apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: slavikb/weatherapp:184
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: weather-service
spec:
  selector:
    app: weather
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
