apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}-service
  labels:
  {{- include "application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: weather
  {{- include "application.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 }}